name: Android NDK

on:
  push:
    tags:
      - '*'

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: "r22"
    steps:
      - name: Create Release (if not exists)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --repo "${{ github.repository }}" \
            --title "${{ github.ref_name }}" \
            --notes "Toolchains" || true

      - name: Download Android NDK
        run: |
          wget -q "https://dl.google.com/android/repository/android-ndk-${{ matrix.version }}-linux-x86_64.zip"

      - name: Upload to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" \
            "android-ndk-${{ matrix.version }}-linux-x86_64.zip" \
            --repo "${{ github.repository }}"
