name: ARM GNU Toolchains

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: "13.3.rel1"
            target: "arm-none-linux-gnueabihf"
          - version: "13.3.rel1"
            target: "aarch64-none-linux-gnu"
    steps:
      - name: Download ARM GNU Toolchain
        run: |
          wget -q "https://developer.arm.com/-/media/Files/downloads/gnu/${{ matrix.version }}/binrel/arm-gnu-toolchain-${{ matrix.version }}-x86_64-${{ matrix.target }}.tar.xz"

      - name: Upload to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" \
            "arm-gnu-toolchain-${{ matrix.version }}-x86_64-${{ matrix.target }}.tar.xz" \
            --repo "${{ github.repository }}"
